package com.android.kotlincoroutines.util

object Constants {

    const val MAIN_SCREEN = "main_screen"
    const val OTHER_SCREEN_ARGUMENT = "type"
    const val OTHER_SCREEN = "other_screen"

    const val SINGLE_API_CALL_SCREEN = "SINGLE API CALL SCREEN"
    const val SERIES_API_CALL_SCREEN = "SERIES API CALL SCREEN"
    const val PARALLEL_API_CALL_SCREEN = "PARALLEL API CALL SCREEN"
    const val ROOM_DB_SCREEN = "ROOM DB SCREEN"
    const val TRY_CATCH_EXCEPTION_HANDLING_SCREEN = "TRY CATCH EXCEPTION HANDLING SCREEN"
    const val EXCEPTION_HANDLER_EXCEPTION_HANDLING_SCREEN = "EXCEPTION HANDLER EXCEPTION HANDLING SCREEN"
    const val SUPERVISOR_EXCEPTION_HANDLING_SCREEN = "SUPERVISOR EXCEPTION HANDLING SCREEN"
    const val TIMEOUT_SCREEN = "TIMEOUT SCREEN"
    const val ONE_LONG_TASK_SCREEN = "ONE LONG TASK SCREEN"
    const val TWO_LONG_TASK_SCREEN = "TWO LONG TASK SCREEN"

    val list = listOf(
        SINGLE_API_CALL_SCREEN,
        SERIES_API_CALL_SCREEN,
        PARALLEL_API_CALL_SCREEN,
        ROOM_DB_SCREEN,
        TRY_CATCH_EXCEPTION_HANDLING_SCREEN,
        EXCEPTION_HANDLER_EXCEPTION_HANDLING_SCREEN,
        SUPERVISOR_EXCEPTION_HANDLING_SCREEN,
        TIMEOUT_SCREEN,
        ONE_LONG_TASK_SCREEN,
        TWO_LONG_TASK_SCREEN
    )

    const val ROOM_TABLE_NAME = "API_USERS"
    const val ROOM_DATABASE_VERSION = 1
    const val ROOM_DATABASE_NAME = "API_USERS_DATABASE"
}